### ISSUE TITLE
kxstudio-default-settings breaks my system

### ISSUE THREAD

**Issue by lucmp** [KXStudio/KXStudio#11]
I spent most of this year annoyed because my audio system was broken, which caused a mess in my patchbays and even forced me to rewrite a few scripts.

Then I upgraded the OS to a new version and thought it would be fixed. It should be. At first it was, but then I did this trick to restore all my packages:

old system:
dpkg --get-selections > /installed-software.txt
new system:
dpkg --set-selections < /installed-software.txt

To my horror, I soon noticed the problem had happened again! I was desperate!

So I reinstalled the system all over again!

But this time I took snapshots/images of the entire file system after installation of every few packages, so I could recover more easily. I eventually zeroed in on 

This is what alsamixer should look like:
![alsamixer-1-normal-50](https://user-images.githubusercontent.com/2882969/31857329-0226464a-b6bb-11e7-96a2-9a2f3b8d2a45.png)

This is what it looks like when the problem happens:
![alsamixer-2-broken-50](https://user-images.githubusercontent.com/2882969/31857321-d9534a1a-b6ba-11e7-9d7c-d6cf3ed042f4.png)

The sound cards are swapped into another order, and that broke some of my scripts. It also makes a mess in my patchbays.

This is what Catia looks like in normal condition:
![catia-1-normal-50](https://user-images.githubusercontent.com/2882969/31857322-e3f94960-b6ba-11e7-890d-1cecf4a95db4.png)

This is what Catia looks like when the system is broken:
![catia-2-broken-50](https://user-images.githubusercontent.com/2882969/31857326-eb5371ea-b6ba-11e7-9e8a-f825820bf542.png)

Then I tried removing kxstudio-default-settings. That fixes the order of the cards and alsamixer, but doesn't clean up the mess in the patchbays.

**Comment by falkTX** [comment]
That's not a mess.. it enables the midi-through ports which can be very handy for passing midi through specific alsa applications to jack ones. This is sometimes required in wine applications, as the alsa midi ports there are not dynamic.

The different initial soundcard is because we enable the alsa loopback module, needed to get alsa->jack bridge working. (unless you prefer using pulseaudio, but some people don't)
it's only an issue if you use hw:0 in your scripts, which to be honest you should not really be doing anyway. (it's safer to use hw:Id, like hw:CODEC or hw:USB, because plugging a USB soundcard, webcam or MIDI device during boot can screw your scripts too - not just the alsa loopback).

Did you ask about this before on the forums or IRC? if so, I apologize as I did not notice.

The way I see it, things are working exactly as intended.

**Comment by lucmp** [comment]
OK then. I guess it's a matter of taste. I think the default-settings way is messy, both because it forced me to select the card manually every time I opened alsamixer and all those MIDI ports in the patchbays look like a big clutter to me. I never needed those, and I use a lot of Windows plugins! 

For the sake of information, FWIW, I can also assure you that I used the alsa->jack bridge for many months, perhaps a full year without these default-settings. I never supposed that kind of arrangement could be intended. Sorry for the trouble. 

I never mentioned this in the forums. It didn't seem appropriate.

Thank you.

**Comment by falkTX** [comment]
the default settings does a lot of things, you just had a setup that was 100% compatible with it.
FWIW I patch alsalib in some kx+ubuntu repos so that loopback is not the first soundcard.
and you should look into not using hw:0 in the future. one day you'll boot a pc with something else that acts as soundcard (midi device, webcam, recorder) and you might wonder why audio does not work anymore.
finally, the midi-through stuff is not used for plugins but for applications.
