### ISSUE TITLE
Ardour4 from package load 3x more DSP than it should

### ISSUE THREAD

**Issue by Houston4444** [KXStudio/KXStudio#5]
Ardour4 from package (4.2.546) load approximatively 3x more DSP as Ardour4 downloaded from site (4.2.0). ardour4-dbg isn't installed on my system, it's really a boring bug, and users could think that ardour is a big consumer.
I tested it on my laptop which isn't up to date (ardour4 from package is 4.2.0) and there is no difference of DSP loading between package's version and downloaded version, so the problem seems to come from new package.

Test is simple, make a new ardour session, add a big number of tracks, and see DSP.

I am not sure that it's a good idea to provide packages between official ardour versions. Ardour releases are regular, and I can't think that ardour team will give a new official version with this kind of trouble.

**Comment by falkTX** [comment]
I know about this, I switched to debug builds for ardour4 to help diagnose some issues.
This is specially important with the gcc5 abi change in some distros.

When ardour4.3 is released officially I guess I'll switch to release (non-debug) builds.
Perhaps having ardour4-dbg provide the full debug version instead of just the symbols.

As for using a in-between releases version, it had to be done because 4.2 broke many plugins.

**Comment by Houston4444** [comment]
Ok cool. I'll use website version waiting for 4.3. 
Moreover, in-between version break many plugins at ardour startup because of buffer troubles (that is said in ardour logs).

**Comment by ahellquist** [comment]
You know that there was no Ardour 4.3 and version 4.4 has been out for a while?

**Comment by falkTX** [comment]
I know yes, there was a suil bug I had to fix first (keys not being passed into some plugins) so now I can update.
It will have to be a git version again.

**Comment by ahellquist** [comment]
No worries. I am patiently waiting. 
Thanks

**Comment by falkTX** [comment]
New update uses release version, not debug.
